Feature/use grpc plugin for user storage
MadAppGang/identifo pull request #128
Opened 2021-01-12 12:54 UTC by esimonov

This PR implements support for pluggable User Storage, and extracts existing user storage solutions to the separate plugins.

2021-01-12 16:35 UTC, esimonov commented
Please don't take failing tests into account - if you look at the error message from the check, you'll see that it's caused by the presence of AWS Lambda integration in this repo. It should have its own repo as it refers to Identifo as a dependency, but that's the subject for a future refactoring.

2021-03-26 05:17 UTC, erudenko requested changes

2021-03-26 05:17 UTC, erudenko commented on cmd/boltdb/main.go
>  package main
@esimonov I believe we need to create other cmd app specific for plugins instead of refactoring boltdb app default app

2021-03-26 05:17 UTC, erudenko commented on cmd/boltdb/main.go
> +	client := plugin.NewClient(&plugin.ClientConfig{
could we encapsulate it inside the servcer implementation?

2021-03-26 05:17 UTC, erudenko commented on cmd/demo/main.go
> +func initServer(plugins shared.Plugins) model.Server {
I believe we need encapsulate all of it in the service implementation

2021-03-26 05:17 UTC, erudenko commented on jwt/service/jwt_token_service.go
> +func NewJWTokenService(keys *model.JWTKeys, issuer string, tokenStorage model.TokenStorage, appStorage model.AppStorage, userStorage shared.UserStorage, options ...func(TokenService) error) (TokenSer
why are we using `shared` instead of `model`

2021-03-26 05:17 UTC, erudenko commented on jwt/service/jwt_token_service.go
> +func (ts *JWTokenService) NewAccessToken(u *proto.User, scopes []string, app model.AppData, requireTFA bool) (ijwt.Token, error) {
I am not sure this is a good idea to connect protobug to this app layer, we need to keep protobuf isolated in the plugin layer.

2021-03-26 05:17 UTC, erudenko commented on jwt/service/jwt_token_service.go
> +			Subject:   u.Id,
it is a good opportunity to replace the `User` interface with the struct model.

2021-03-26 05:17 UTC, erudenko commented on plugin/shared/grpc.go
> +package shared
what is the idea of havin shared package in plugin folder?

2021-03-26 05:17 UTC, erudenko commented on plugin/shared/grpc.go
> +func (m *GRPCServer) UserByID(ctx context.Context, req *proto.UserByIDRequest) (*proto.User, error) {
looks like we have both GRPC server and client in one file that does the same thing?

2021-03-26 05:17 UTC, erudenko commented on plugin/shared/grpc.go
> +	Impl UserStorage
I am not sure what do you mean here?

2021-03-26 05:17 UTC, erudenko commented on plugin/shared/grpc.go
> +func (m *GRPCServer) UserByPhone(ctx context.Context, req *proto.UserByPhoneRequest) (*proto.User, error) {
why are we returning pointe, as I understand proto.User is just a struct.

2021-03-26 05:17 UTC, erudenko commented on plugin/shared/interface.go
> +package shared
I believe we need organise it by functional parts.

2021-08-02 12:20 UTC, closed without merging